<?xml version="1.0" encoding="utf-8"?><Database Name="WhatsApp" Class="IFZAPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-F1JDHKU\SQLEXPRESS;Initial Catalog=WhatsApp;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WhatsAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Uri" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Foto" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Usuario_Membro" Member="Membros" ThisKey="Id" OtherKey="Usuario_Id" Type="Membro" />
    </Type>
  </Table>
  <Table Name="dbo.Grupo" Member="Grupos">
    <Type Name="Grupo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IdAdm" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Grupo_Membro" Member="Membros" ThisKey="Id" OtherKey="Grupo_Id" Type="Membro" />
    </Type>
  </Table>
  <Table Name="dbo.Membros" Member="Membros">
    <Type Name="Membro">
      <Column Name="Usuario_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Grupo_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Grupo_Membro" Member="Grupo" ThisKey="Grupo_Id" OtherKey="Id" Type="Grupo" IsForeignKey="true" />
      <Association Name="Usuario_Membro" Member="Usuario" ThisKey="Usuario_Id" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
</Database>